Parcker/Controllers/PagarReceberController.cs
using Parcker.Domain;
using Parcker.Models;
using Parcker.Models.Enums;
using Parcker.Repository.Business;
using System.Linq.Dynamic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Rotativa;
using Rotativa.Options;

namespace Parcker.Controllers
{
    public class PagarReceberController : BaseController
    {
        // GET: PagarReceber
        public ActionResult Index()
        {
            var formaPagamentoColletion = new List<SelectListItem>();
            formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.Dinheiro).ToString(), Text = "Dinheiro" });
            formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.CartaoCredito).ToString(), Text = "Cartão de Crédito" });
            formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.CartaoDebito).ToString(), Text = "Cartão de Débito" });
            formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.Boleto).ToString(), Text = "Boleto" });
            formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.Cheque).ToString(), Text = "Cheque" });
            formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.Deposito).ToString(), Text = "Depósito" });
            formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.TransferenciaBancaria).ToString(), Text = "Transferência Bancária" });
            ViewBag.FormaPagamento = formaPagamentoColletion;

            return View();
        }

        public ActionResult Edit(int? id)
        {
            using (var entity = new Entity())
            {
                ViewBag.Pessoas = new List<Pessoa>().Select(x => new SelectListItem()).ToList();
                ViewBag.Classificacao = entity.All<Classificacao>().Select(x => new SelectListItem() { Text = x.Descricao, Value = x.Id.ToString() }).ToList();

                var formaPagamentoColletion = new List<SelectListItem>();
                formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.Dinheiro).ToString(), Text = "Dinheiro" });
                formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.CartaoCredito).ToString(), Text = "Cartão de Crédito" });
                formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.CartaoDebito).ToString(), Text = "Cartão de Débito" });
                formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.Boleto).ToString(), Text = "Boleto" });
                formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.Cheque).ToString(), Text = "Cheque" });
                formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.Deposito).ToString(), Text = "Depósito" });
                formaPagamentoColletion.Add(new SelectListItem() { Value = ((int)FormasPagamentoEnum.TransferenciaBancaria).ToString(), Text = "Transferência Bancária" });
                ViewBag.FormaPagamento = formaPagamentoColletion;

                if (!id.HasValue || id == 0)
                    return View(new PagarReceberModel()
                    {
                        IdTipoConta = TipoContaEnum.Receber,
                        DataCriacao = DateTime.Now,
                        GrupoParcela = 0,
                        Parcela = 1,
                        TotalParcela = 1,
                        IdFormaPagamento = FormasPagamentoEnum.Dinheiro,
                        IdSituacaoConta = SituacaoContaEnum.Pendente,
                        Valor = 0,
                        Descricao = "Não informada"
                    });
                else
                {
                    var modelMap = Mapper.Map<PagarReceberModel>(entity.GetById<PagarReceber>(id.Value));
                    if (modelMap != null)
                    {
                        ViewBag.Pessoas = entity.All<Pessoa>()
                            .Where(x => x.Id == modelMap.IdPessoa)
                            .Select(x => new SelectListItem()
                            {
                                Text = $"{(x.Tipo == (int)TipoPessoaEnum.Fisica ? (x.CPF + " - " + x.Nome) : (x.CNPJ + " - " + x.RazaoSocial))}",
                                Value = x.Id.ToString()
                            }).ToList();

                        if (modelMap.IdFormaPagamento == FormasPagamentoEnum.CartaoCredito)
                        {
                            modelMap = Mapper.Map<PagarReceberModel>(entity.GetById<PagarReceber>(modelMap.GrupoParcela));
                            modelMap.Valor = modelMap.Valor * modelMap.TotalParcela;
                        }
                    }

                    return View(modelMap != null ? modelMap : new PagarReceberModel()
                    {
                        DataCriacao = DateTime.Now,
                        GrupoParcela = 0,
                        Parcela = 1,
                        TotalParcela = 1,
                        IdFormaPagamento = FormasPagamentoEnum.Dinheiro,
                        IdSituacaoConta = SituacaoContaEnum.Pendente,
                        Valor = 0,
                        Descricao = "Não informada"
                    });
                }
            }
        }

        public ActionResult RelatorioFluxoCaixa()
        {
            var m = DateTime.Now.Month > 1 ? DateTime.Now.Month - 1 : 12;
            var y = DateTime.Now.Month > 1 ? DateTime.Now.Year : DateTime.Now.Year - 1;
            return View(new PrinterPRModel()
            {
                DataInicio = new DateTime(y, m, 1),
                DataFinal = new DateTime(y, m, DateTime.DaysInMonth(y, m)),
                GerarPDF = false
            });
        }

        [HttpPost]
        public PartialViewResult PrinterViewer(PrinterPRModel filtro)
        {
            if (ModelState.IsValid)
            {
                using (var entity = new Entity())
                {
                    var model = new PrinterPRModel()
                    {
                        Usuario = entity.All<Usuario>().Where(x => x.Nome == User.Identity.Name).FirstOrDefault(),
                        PagarReceber = entity.All<PagarReceber>()
                            .Where(x => x.DataPagamento >= filtro.DataInicio
                                && x.DataPagamento <= filtro.DataFinal
                                && filtro.IdSituacaoConta.Contains(x.IdSituacaoConta)
                                && filtro.IdFormaPagamento.Contains(x.IdFormaPagamento))
                            .OrderBy(x => x.DataPagamento)
                            .ToList(),
                        DataInicio = filtro.DataInicio,
                        DataFinal = filtro.DataFinal,
                        GerarPDF = filtro.GerarPDF,
                        IdFormaPagamento = filtro.IdFormaPagamento,
                        IdSituacaoConta = filtro.IdSituacaoConta
                    };

                    return PartialView(model);
                }
            }
            return PartialView(null);
        }

        [HttpPost]
        public ActionResult Printer(PrinterPRModel filtro)
        {
            if (ModelState.IsValid)
            {
                using (var entity = new Entity())
                {
                    var model = new PrinterPRModel()
                    {
                        Usuario = entity.All<Usuario>().Where(x => x.Nome == User.Identity.Name).FirstOrDefault(),
                        PagarReceber = entity.All<PagarReceber>()
                            .Where(x => x.DataPagamento >= filtro.DataInicio
                                && x.DataPagamento <= filtro.DataFinal
                                && filtro.IdSituacaoConta.Contains(x.IdSituacaoConta)
                                && filtro.IdFormaPagamento.Contains(x.IdFormaPagamento))
                            .OrderBy(x => x.DataPagamento)
                            .ToList(),
                        DataInicio = filtro.DataInicio,
                        DataFinal = filtro.DataFinal,
                        GerarPDF = filtro.GerarPDF,
                        IdFormaPagamento = filtro.IdFormaPagamento,
                        IdSituacaoConta = filtro.IdSituacaoConta
                    };
                    if (filtro.GerarPDF)
                    {
                        model.GerarPDF = false;
                        return new ViewAsPdf()
                        {
                            FileName = $"Impressao_Relatorio_Caixa_{DateTime.Now.ToShortDateString()}.pdf",
                            ViewName = "Printer",
                            PageSize = Size.A4,
                            IsGrayScale = false,
                            Model = model
                        };
                    }
                    else
                    {
                        model.GerarPDF = true;
                        return View(model);
                    }
                }
            }
            return PartialView(null);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(PagarReceberModel model)
        {
            if (!ModelState.IsValid)
                return Json(new { IsValid = false, Message = MensagemValidacao }, JsonRequestBehavior.AllowGet);
            else
                using (var entity = new Entity())
                {
                    try
                    {
                        entity.BeginTransaction();

                        var modelMap = Mapper.Map<PagarReceber>(model);
                        if (model.Id == 0)
                        {
                            var grupoParcela = 0;
                            var dataPagamento = modelMap.DataPagamento ?? DateTime.Now;

Parcker/Views/PagarReceber/Index.cshtml
@model Parcker.Models.PagarReceberModel
@{
    ViewBag.Title = "Pagar e Receber";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{
    @Styles.Render("~/plugin/dtable/css")
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Pagar e Receber</h1>
    <p class="mb-4">Gerencie suas entradas e saídas e acompanhe o fluxo de caixa no dashboard da tela inicial.</p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header">
            <form id="formFilter">
                <div class="row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.IdTipoConta, htmlAttributes: new { @class = "control-label" })
                        @Html.EnumDropDownListFor(model => model.IdTipoConta, "Pagar e Receber", new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-2">
                        @Html.LabelFor(model => model.DataPagamento, htmlAttributes: new { @class = "control-label" })
                        @Html.TextBoxFor(model => model.DataPagamento, new { @class = "form-control date" })
                    </div>
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.IdFormaPagamento, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(model => model.IdFormaPagamento, ViewBag.FormaPagamento as IEnumerable<SelectListItem>, "Todas", new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-2 pt-1">
                        <button type="submit" class="btn btn-block btn-primary mt-4"><i class="fa fa-filter"></i>&nbsp;Filtrar</button>
                    </div>
                    <div class="form-group col-md-2 pt-1">
                        <a href="@Url.Action("Edit")" class="btn btn-block btn-success mt-4"><i class="fa fa-plus"></i>&nbsp;Lançamento</a>
                    </div>
                </div>
            </form>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <!-- Page level plugins -->
    @Scripts.Render("~/plugin/dtable/js")

    <!-- Page level custom scripts -->
    @Scripts.Render("~/views/pagarreceber/js")

    <script type="text/javascript">
        $(document).ready(function () {
            $("#menu-pagar-receber").addClass("active");
        });
    </script>
}

Parcker/Views/PagarReceber/Printer.cshtml
@model Parcker.Models.PrinterPRModel
@using Parcker.Models.Enums
@{
    Layout = null;
    ViewBag.Title = "Impressão";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Impressão de Relatório de Fluxo de Caixa - Oficina Parcker</title>
    @Styles.Render("~/impressao/css")
    @Scripts.Render("~/impressao/js")
    <link rel="shortcut icon" type="image/png" href="@Url.Content("~/Content/img/logo_icon.png")" />
    <style type="text/css">
        @@page {
            size: A4;
        }

        table {
            font-size: 12px;
        }
    </style>
</head>
<body class="container">
    @if (Model == null)
    {
        <text>
            <p class="lead pt-3 text-center">Não foi possível gerar o relatório.</p>
        </text>
    }
    else
    {
        <text>
            <section class="sheet padding-10mm">
                <div class="text-right no-print">
                    @if (Model.GerarPDF)
                    {
                        using (Html.BeginForm("Printer", "PagarReceber", FormMethod.Post, new { @target = "_blank" }))
                        {
                            @Html.HiddenFor(x => x.DataInicio)
                            @Html.HiddenFor(x => x.DataFinal)

                            <input type="hidden" name="GerarPDF" id="GerarPDF" value="@Model.GerarPDF.ToString()" />

                            for (int i = 0; i < Model.IdFormaPagamento.Length; i++)
                            {
                                @Html.HiddenFor(model => Model.IdFormaPagamento[i])
                            }

                            for (int i = 0; i < Model.IdSituacaoConta.Length; i++)
                            {
                                @Html.HiddenFor(model => Model.IdSituacaoConta[i])
                            }
                            <button type="submit" class="btn btn-link"><i class="fa fa-file-pdf"></i>&nbsp;GERAR PDF</button>
                        }
                    }
                </div>
                <article class="text-center mb-0">
                    <table class="table table-borderless mb-0">
                        <tr>
                            <td width="250" class="text-left pl-0"><img src="@Url.Content("~/Content/img/logo.png")" width="250" /></td>
                            <td width="250" class="text-right pr-0">
                                @if (Model.Usuario.Pessoa != null)
                                {
                                    <p class="lead">
                                        @if (Model.Usuario.Pessoa.Tipo == (int)TipoPessoaEnum.Fisica)
                                        {
                                            <text>
                                                @Model.Usuario.Pessoa.Nome
                                            </text>
                                        }
                                        else
                                        {
                                            <text>
                                                @Model.Usuario.Pessoa.Fantasia
                                            </text>
                                        }
                                    </p>
                                    <div class="mb-4">
                                        @if (Model.Usuario.Pessoa.Tipo == (int)TipoPessoaEnum.Fisica)
                                        {
                                            <small>Nome: </small> @Model.Usuario.Pessoa.Nome<br />
                                            <small>CPF: </small> @Model.Usuario.Pessoa.CPF<br />
                                            <small>Telefone: </small> @(Model.Usuario.Pessoa.Telefone1 + " | " + Model.Usuario.Pessoa.Telefone2)<br />
                                            <small>Endereço: </small> @(Model.Usuario.Pessoa.Endereco + ", n° " + Model.Usuario.Pessoa.Numero + ", " + Model.Usuario.Pessoa.Bairro + " - " + Model.Usuario.Pessoa.Cidade + "/" + Model.Usuario.Pessoa.UF)<br />
                                        }
                                        else
                                        {
                                            <small>Razão Social: </small> @Model.Usuario.Pessoa.RazaoSocial<br />
                                            <small>CNPJ: </small> @Model.Usuario.Pessoa.CNPJ<br />
                                            <small>Telefone: </small> @(Model.Usuario.Pessoa.Telefone1 + " | " + Model.Usuario.Pessoa.Telefone2)<br />
                                            <small>Endereço: </small> @(Model.Usuario.Pessoa.Endereco + ", n° " + Model.Usuario.Pessoa.Numero + ", " + Model.Usuario.Pessoa.Bairro + " - " + Model.Usuario.Pessoa.Cidade + "/" + Model.Usuario.Pessoa.UF)<br />
                                        }
                                    </div>
                                }
                                else
                                {
                                    <p class="lead"></p>
                                    <div class="mb-4"></div>
                                }
                            </td>
                    </table>
                </article>
                <h4>Extrato do Período</h4>
                <p class="lead">@Model.DataInicio.ToString("dd/MM/yyyy") até @Model.DataFinal.ToString("dd/MM/yyyy")</p>
                <table class="table">
                    <thead>
                        <tr>
                            <th width="30"></th>
                            <th width="80">Pagamento</th>
                            <th width="80">Vencimento</th>
                            <th width="170">Classificação</th>
                            <th width="200">Cobrador/Pagante</th>
                            <th width="150">Forma Pagamento</th>
                            <th>Descrição</th>
                            <th width="100" class="text-right">Valor</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            var index = 1;
                            foreach (var item in Model.PagarReceber)
                            {
                                <tr>
                                    <td>@index</td>
                                    <td>@item.DataPagamento.Value.ToString("dd/MM/yyyy")</td>
                                    <td>@(item.DataVencimento.HasValue ? item.DataVencimento.Value.ToString("dd/MM/yyyy") : "")</td>
                                    <td>@item.Classificacao.Descricao</td>
                                    <td>@(string.IsNullOrEmpty(item.Pessoa?.Nome ?? "") ? item.Pessoa?.RazaoSocial ?? "" : item.Pessoa?.Nome ?? "")</td>
                                    <td>@item.FormasPagamento.Descricao</td>
                                    <td>@item.Descricao</td>
                                    <td class="text-right @(item.IdTipoConta == (int)TipoContaEnum.Pagar ? "text-danger" : "text-success")">@(item.IdTipoConta == (int)TipoContaEnum.Pagar ? "-" : "") R$ @item.Valor.ToString("N2")</td>
                                </tr>

                                index++;
                            }
                        }
                    </tbody>
                </table>
                @{
                    var totalDespesas = Model.PagarReceber.Where(x => x.IdTipoConta == (int)TipoContaEnum.Pagar).Sum(x => x.Valor);
                    var totalReceitas = Model.PagarReceber.Where(x => x.IdTipoConta == (int)TipoContaEnum.Receber).Sum(x => x.Valor);
                    var saldo = totalReceitas - totalDespesas;
                }
                <table class="table table-borderless" style="margin-top:20px;">
                    <tr>
                        <td width="250" class="text-right">
                            <p>Total Despesas</p>
                            <p class="lead">R$ @totalDespesas.ToString("N2")</p>
                        </td>
                        <td width="250" class="text-right">
                            <p>Total Receitas</p>
                            <p class="lead">R$ @totalReceitas.ToString("N2")</p>
                        </td>
                        <td width="250" class="text-right">
                            <p>Saldo Geral</p>
                            @if (saldo < 0)
                            {
                                <p class="lead text-danger">R$ @saldo.ToString("N2")</p>
                            }
                            else
                            {
                                <p class="lead text-success">R$ @saldo.ToString("N2")</p>
                            }
                        </td>
                    </tr>
                </table>
            </section>
        </text>
    }

    <script type="text/javascript">
        var URLBase = "@(Url.Content("~/"))";
    </script>
</body>
</html>

Parcker/Views/PagarReceber/PrinterViewer.cshtml
@using Parcker.Models.Enums;
@model Parcker.Models.PrinterPRModel

@if (Model == null)
{
    <text>
        <p class="lead pt-3 text-center">Não foi possível gerar o relatório.</p>
    </text>
}
else
{
    <text>
        <table class="table">
            <thead>
                <tr>
                    <th width="30"></th>
                    <th width="80">Pagamento</th>
                    <th width="80">Vencimento</th>
                    <th width="170">Classificação</th>
                    <th width="200">Cobrador/Pagante</th>
                    <th width="150">Forma Pagamento</th>
                    <th>Descrição</th>
                    <th width="100" class="text-right">Valor</th>
                </tr>
            </thead>
            <tbody>
                @{
                    var index = 1;
                    foreach (var item in Model.PagarReceber)
                    {
                        <tr>
                            <td>@index</td>
                            <td>@item.DataPagamento.Value.ToString("dd/MM/yyyy")</td>
                            <td>@(item.DataVencimento.HasValue ? item.DataVencimento.Value.ToString("dd/MM/yyyy") : "")</td>
                            <td>@item.Classificacao.Descricao</td>
                            <td>@(string.IsNullOrEmpty(item.Pessoa?.Nome ?? "") ? item.Pessoa?.RazaoSocial ?? "" : item.Pessoa?.Nome ?? "")</td>
                            <td>@item.FormasPagamento.Descricao</td>
                            <td>@item.Descricao</td>
                            <td class="text-right @(item.IdTipoConta == (int)TipoContaEnum.Pagar ? "text-danger" : "text-success")">@(item.IdTipoConta == (int)TipoContaEnum.Pagar ? "-" : "") R$ @item.Valor.ToString("N2")</td>
                        </tr>

                        index++;
                    }
                }
            </tbody>
        </table>

        @{
            var totalDespesas = Model.PagarReceber.Where(x => x.IdTipoConta == (int)TipoContaEnum.Pagar).Sum(x => x.Valor);
            var totalReceitas = Model.PagarReceber.Where(x => x.IdTipoConta == (int)TipoContaEnum.Receber).Sum(x => x.Valor);
            var saldo = totalReceitas - totalDespesas;
        }

        <table class="table table-borderless" style="margin-top:20px;">
            <tr>
                <td width="250" class="text-right">
                    <p>Total Despesas</p>
                    <p class="lead">R$ @totalDespesas.ToString("N2")</p>
                </td>
                <td width="250" class="text-right">
                    <p>Total Receitas</p>
                    <p class="lead">R$ @totalReceitas.ToString("N2")</p>
                </td>
                <td width="250" class="text-right">
                    <p>Saldo Geral</p>
                    @if (saldo < 0)
                    {
                        <p class="lead text-danger">R$ @saldo.ToString("N2")</p>
                    }
                    else
                    {
                        <p class="lead text-success">R$ @saldo.ToString("N2")</p>
                    }
                </td>
            </tr>
        </table>
    </text>
}

Parcker/Views/PagarReceber/RelatorioFluxoCaixa.cshtml
@using Parcker.Extension
@model Parcker.Models.PrinterPRModel
@{
    ViewBag.Title = "Relatório Fluxo de Caixa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{
    <!-- Page level plugins -->
    @Styles.Render("~/plugin/autocomplete/css")
}

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Relatório Fluxo de Caixa</h1>
    <p id="page-title" class="mb-4">
        Aqui você pode gerar relatórios de fluxo de caixa por período, status e formas de pagamento.
    </p>

    <div class="card shadow mb-4">
        <div class="card-body">
            @using (Html.BeginForm("Printer", "PagarReceber", FormMethod.Post, new { @target = "_blank" }))
            {
                @Html.HiddenFor(x => x.GerarPDF)
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Data Início</label>
                            @Html.TextBoxFor(x => x.DataInicio, new { @class = "form-control date" })
                            @Html.ValidationMessageFor(x => x.DataInicio, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Data Final</label>
                            @Html.TextBoxFor(x => x.DataFinal, new { @class = "form-control date" })
                            @Html.ValidationMessageFor(x => x.DataFinal, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label>Situações</label>
                            <select id="IdSituacaoConta" multiple name="IdSituacaoConta" class="form-control selectpicker">
                                <option value="1">Pendente</option>
                                <option value="2" selected>Pago</option>
                                <option value="3">Inativo</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Formas de Pagamento</label>
                            <select id="IdFormaPagamento" multiple name="IdFormaPagamento" class="form-control selectpicker">
                                <option value="1" selected>Boleto</option>
                                <option value="2" selected>Dinheiro</option>
                                <option value="3" selected>Cartão de Crédito</option>
                                <option value="4" selected>Cartão de Débito</option>
                                <option value="5" selected>Cheque</option>
                                <option value="6" selected>Transferência Bancária</option>
                                <option value="7" selected>Depósito</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group pt-2 text-center">
                            <button id="btnVisualizar" type="button" class="btn btn-outline-primary btn-block mt-4"><i class="fa fa-eye"></i>&nbsp;Visualizar</button>
                        </div>
                    </div>
                    <div class="col-md-1">
                        <div class="form-group pt-2 text-center">
                            <button id="btnSubmit" type="submit" title="Imprimir" class="btn btn-primary btn-block mt-4"><i class="fa fa-print"></i></button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    <div class="card shadow mb-4">
        <div id="containerRelatorio" class="card-body">
            <p class="lead pt-3 text-center">Nenhum relatório foi visualizado.</p>
        </div>
    </div>
</div>

@section Scripts{
    <!-- Page level plugins -->
    @Scripts.Render("~/plugin/autocomplete/js")

    <!-- Page level custom scripts -->
    @Scripts.Render("~/views/pagarreceber/relatoriofluxocaixa/js")

    <script type="text/javascript">
        $('.selectpicker').selectpicker({
            noneSelectedText: 'Selecione...'
        });

        $(document).ready(function () {
            $("#menu-relatorio").addClass("active");
        });
    </script>
}